### ISSUE TITLE
Addon broken since latest update

### ISSUE THREAD

**Issue by dagochen** [evil-morfar/RCLootCouncil_Classic#62]
Raiding on Classic HC Fresh Anniversary Servers.

The addon does not work anymore:
- Can not choose disenchanter anymore
- In the overview where you can vote for players and items, the rows jump around like crazy
- items were not recognized on looting
- not asking for starting session with rclc

**Comment by evil-morfar** [comment]
Should be fixed with v1.0.1

**Comment by dagochen** [comment]
We will try out and see what happens ;)

**Comment by dagochen** [comment]
Addon still not working:
- Can not choose disenchanter anymore
- In the overview where you can vote for players and items, the rows jump around like crazy

https://youtu.be/o4NeYUcUb9A

**Comment by evil-morfar** [comment]
I'll have another look then.

On a side note, did you feel a performance difference running that many items in a session?

**Comment by evil-morfar** [comment]
I can't replicate your disenchant issues, it works fine on my end. To investigate, I'd need your saved variables, although it may not help if it's more than two days ago since you tried.

It's located at `../World of Warcraft/_classic_era_/WTF/Account/"account_name"/SavedVariables/RCLootCouncil_Classic.lua`

**Comment by evil-morfar** [comment]
Although in your video you're not the ML - and council members don't see the disenchant button :D

**Comment by dagochen** [comment]
I mean thats only 1 of the problems.....clicking an item and rewarding does always show the same player.

**Comment by evil-morfar** [comment]
Sounds like you're getting lua errors. I really need your SV to investigate it

**Comment by dagochen** [comment]
https://gist.github.com/dagochen/9b43716f2d51234eec6f5622ace76b1d

**Comment by dagochen** [comment]
<img width="724" height="153" alt="Image" src="https://github.com/user-attachments/assets/1698d1fd-60ca-4038-bb0b-ead20937f11c" />

**Comment by evil-morfar** [comment]
> I mean thats only 1 of the problems.....clicking an item and rewarding does always show the same player.

Not entirely sure what you mean by this - you talking about reawarding or awarding?


> <img alt="Image" width="724" height="153" src="https://private-user-images.githubusercontent.com/5236186/465653782-1698d1fd-60ca-4038-bb0b-ead20937f11c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI1Njk4NjksIm5iZiI6MTc1MjU2OTU2OSwicGF0aCI6Ii81MjM2MTg2LzQ2NTY1Mzc4Mi0xNjk4ZDFmZC02MGNhLTQwMzgtYmIwYi1lYWQyMDkzN2YxMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MTVUMDg1MjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmZiZGI3MjBjZWE0MGUxMTAzZjhlOGZjMmFmOTEyZDNjNzg2NjE3ZWQ1MDdiYzBiYmNiZDE4NTUxZjdjYzM1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.r4OubAY4T2rykIUn5TDwGMSfc4vtyctL5lwD7RloCr0">

Don't add your own pass button - it's done automatically

**Comment by dagochen** [comment]
I am not adding anything. That happened to all of us.

**Comment by evil-morfar** [comment]
Have you tried with the latest version?
